### ISSUE TITLE
Currency not supported by merchant error

### ISSUE THREAD

**Issue by olumytee** [Kendysond/Prestashop-Paystack#1]
Hi, currently having an issue with the plugin. Using Prestashop 1.6.1.7, default currency is set to Naira but I still get the following error. Kindly help
![pstack](https://cloud.githubusercontent.com/assets/463900/19010748/af3254f0-877d-11e6-9fb0-bd81ca3de137.JPG)

**Comment by Kendysond** [comment]
Hello Olumide, 
Kindly confirm your public key is correct. This issue is caused by incorrect public key.

**Comment by olumytee** [comment]
Hello, thanks. That solved it. But I have new issues, sorry I'm new to Prestashop. 
1. I can't seem to move from Test keys to Live keys as the Live Keys input box stays empty even after I've saved it a couple of times like so
![pic2](https://cloud.githubusercontent.com/assets/463900/19013780/e089f940-87d2-11e6-840b-152a39e06bda.JPG)


and 2. The order summary page doesn't seem to update, after I completed the first orde, I tried another one but the details of the olf one are still being shown hence throwing a Duplicate Transaction Referebce Error when I try to complete the order
![page1](https://cloud.githubusercontent.com/assets/463900/19013784/ef7e516c-87d2-11e6-890b-90612a4556a1.png)


Thank you

**Comment by Kendysond** [comment]
Hello Olumide, 

I just noticed the error too. Sorry about that. I just pushed a fix for the live secret key. What I can't really diagnose at the moment is the order summary. But I'm still looking into it. let me know if this solves your problem though.

**Comment by olumytee** [comment]
Hi Douglas, The update fixed the live keys issue. Thanks. It seems to fix the cart summary error too but the Duplicate Transaction Reference error persists.  I'll poke around the code to see what I can do.

**Comment by Kendysond** [comment]
Hello Olumide, 
I just pushed another update to fix the error of duplicate transaction reference. You can try it and let me know.

**Comment by olumytee** [comment]
Hi Douglas, unfortunately it hasnt fixed it, and the old issue is back, that of keys not saving (Test Public Key and The Live/ Public radio button this time) it has stopped showing up on the checkout page

**Comment by Kendysond** [comment]
Did you do the cache thing? You can add me on Skype douglas_3355

**Comment by olumytee** [comment]
I have done disabled cache, I will add you on skype now. Thanks.

**Comment by Bharavi26** [comment]
set currency **NGN** and my account is in test mode, while i am testing with test card it show currency not supported by merchant, also i double check my publick test key.

**Comment by Palo-Foods** [comment]
@Bharavi26 Same here. I can't seem to figure out the problem. Even if you add or remove the currency prop, you get same error

**Comment by Palo-Foods** [comment]
> Hello Olumide, Kindly confirm your public key is correct. This issue is caused by the incorrect public key.

Done all that is required, I still get the same issue. Whether the currency prop exist or not
